### ISSUE TITLE
Error after running Recon

### ISSUE THREAD

**Issue by rangerrkm** [secgroundzero/warberry#100]
Hello,

I just ran a Recon and after it was almost complete, i got this error.

Traceback (most recent call last):
  File "wrapper.py", line 199, in <module>
    warberry()
  File "wrapper.py", line 179, in warberry
    create_xmls()
  File "/home/pi/WarBerry/warberry/xml_producer.py", line 125, in create_xmls
    create_xml("../Results/hostnames", "hostnames")
  File "/home/pi/WarBerry/warberry/xml_producer.py", line 179, in create_xml
    root)).toprettyxml()  # Since ElementTree write() has no pretty printing support, used minidom to beautify the xml.
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 17

I thought that is was with optparse-pretty and that did not help me.

Any ideas on what to try

Also, has anyone tried the -h or --help and instead of just showing you the help menu, it starts running.

Thanks,

**Comment by secgroundzero** [comment]
new version coming out to address this
