### ISSUE TITLE
launch script warberry.py

### ISSUE THREAD

**Issue by denver27** [secgroundzero/warberry#102]
after a clean reinstallation, launching warberry.py :

```
Traceback (most recent call last):
  File "warberry.py", line 66, in <module>
    warberry()
  File "warberry.py", line 59, in warberry
    x = Warberry(options)
  File "/home/al/warberry-master/warberry-master/src/warberrySetup/Warberry.py", line 34, in __init__
    warberryDB.insertSession()
  File "/home/al/warberry-master/warberry-master/src/warberrySetup/WarberryDB.py", line 43, in insertSession
    warberryID=result[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
root@kali:/home/al/warberry-master/warberry-master#

```

**Comment by sconst** [comment]
Please check whether the warberry.db is created.

**Comment by denver27** [comment]
warberry.db is present in the same place where the script is launched : 
/home/al/warberry-master/warberry-master/

**Comment by Se1ecto** [comment]
I manually ran WarberryModel.py and the initial script started working.
Did you try it out?

**Comment by denver27** [comment]
running "warberry.py" after "WarberryModel.py" is working. 
I forgot something ? Must always run that one before?
warberry.py script has not finished yet (very long) but for the moment no error.
thank you very much !

**Comment by sconst** [comment]
No, you don't have to run "WarberryModel.py". WarberryModel.py is executed upon warberry's installation in order to determine Raspberry's model .
Setup.sh updated. 
You could use the " -Q" option in order to perform services' scanning using threads and/or the "-i" option to perform port scanning with higher (quicker) intensity i.e -T4 . In addition, Responder's default timeout is 900s.  Please refer to Wiki Page & warberry's manual for more information.

Thank you.

**Comment by sconst** [comment]
Issue Resolved. Closed.

**Comment by apkchel** [comment]
I can not start Warberry error

Traceback (most recent call last):
  File "warberry.py", line 66, in <module>
    warberry()
  File "warberry.py", line 59, in warberry
    x = Warberry(options)
  File "/root/warberry/src/warberrySetup/Warberry.py", line 34, in __init__
    warberryDB.insertSession()
  File "/root/warberry/src/warberrySetup/WarberryDB.py", line 40, in insertSession
    db=(modelPI,)
UnboundLocalError: local variable 'modelPI' referenced before assignment
