### ISSUE TITLE
Viewing Data

### ISSUE THREAD

**Issue by hunttom** [secgroundzero/warberry#108]
Hello all: I am unable to view data. I tried opening up index.html after configuring Reporting/Results as per the innstructions. Furthermore, I have tried running apache to see if it wasn't a service that was causing the website to break. Still unable to view data. What am I missing from the instructions?

Also: I am getting this error despite running the DNS install script.
```
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 7, in <module>
    from cme.crackmapexec import main
  File "/usr/local/lib/python2.7/dist-packages/cme/crackmapexec.py", line 10, in <module>
    from cme.connection import Connection
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cme/connection.py", line 8, in <module>
    from impacket.smbconnection import SMBConnection, SessionError
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 20, in <module>
    from impacket import smb, smb3, nmb, nt_errors, LOG
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 49, in <module>
    from pyasn1.type.univ import noValue
ImportError: cannot import name noValue
```

**Comment by sconst** [comment]
We will check the above.
 
For the current version, you could use Reporting Module to view the data.

Thanks.
