### ISSUE TITLE
ModelPi UnboundLocalError

### ISSUE THREAD

**Issue by 0x023** [secgroundzero/warberry#110]
Hi,

Unfortunately running the setup.sh triggered following error:

Traceback (most recent call last):
  File "warberryModel.py", line 30, in <module>
    x.insertWarBerryModel()
  File "warberryModel.py", line 20, in insertWarBerryModel
    db_in=("WarberryPI", modelPI)
UnboundLocalError: local variable 'modelPI' referenced before assignment

Could you please advise ?
Thanks :)

**Comment by HSIS007** [comment]
I am also facing this error while executing warberry.py.

**Comment by matsuro-i** [comment]
You have to edit line 34 in ../src/warberrySetup/WarberryDB.py

If you do cat /proc/cpuinfo you will notice that the return is revision : 3 or something. Line 34 is trying to grep for Revision but your cpuinfo is returning revision with the a lower case r.  You might have to change print $3 to $4 as well to get this to work.
