### ISSUE TITLE
struct.error: cannot convert argument to integer

### ISSUE THREAD

**Issue by Sh0cker** [secgroundzero/warberry#112]
Traceback (most recent call last):
  File "./warberry.py", line 19, in <module>
    from src.warberrySetup.Warberry import *
  File "/home/sh0ck3r/Desktop/SK/UsefulTools/warberry/src/warberrySetup/Warberry.py", line 2, in <module>
    from src.warberrySetup.WarberryInformationGathered import *
  File "/home/sh0ck3r/Desktop/SK/UsefulTools/warberry/src/warberrySetup/WarberryInformationGathered.py", line 3, in <module>
    from src.core.enumeration.hostnames import *
  File "/home/sh0ck3r/Desktop/SK/UsefulTools/warberry/src/core/enumeration/hostnames.py", line 21, in <module>
    from dns import resolver
  File "build/bdist.linux-x86_64/egg/dns/resolver.py", line 33, in <module>
  File "build/bdist.linux-x86_64/egg/dns/message.py", line 36, in <module>
  File "build/bdist.linux-x86_64/egg/dns/rrset.py", line 24, in <module>
  File "build/bdist.linux-x86_64/egg/dns/renderer.py", line 26, in <module>
  File "build/bdist.linux-x86_64/egg/dns/tsig.py", line 64, in <module>
  File "build/bdist.linux-x86_64/egg/dns/name.py", line 912, in from_text

**Comment by brahmanggi** [comment]
trying to install on raspi 4 4gb , got an error

> Traceback (most recent call last):
  File "warberry.py", line 19, in <module>
    from src.warberrySetup.Warberry import *
  File "/root/warberry/src/warberrySetup/Warberry.py", line 2, in <module>
    from src.warberrySetup.WarberryInformationGathered import *
  File "/root/warberry/src/warberrySetup/WarberryInformationGathered.py", line 3, in <module>
    from src.core.enumeration.hostnames import *
  File "/root/warberry/src/core/enumeration/hostnames.py", line 21, in <module>
    from dns import resolver
  File "build/bdist.linux-armv7l/egg/dns/resolver.py", line 33, in <module>
  File "build/bdist.linux-armv7l/egg/dns/message.py", line 36, in <module>
  File "build/bdist.linux-armv7l/egg/dns/rrset.py", line 24, in <module>
  File "build/bdist.linux-armv7l/egg/dns/renderer.py", line 26, in <module>
  File "build/bdist.linux-armv7l/egg/dns/tsig.py", line 64, in <module>
  File "build/bdist.linux-armv7l/egg/dns/name.py", line 912, in from_text
struct.error: cannot convert argument to integer

**Comment by yrjo** [comment]
the same for latest rpi0-w. on kali with nexus:
4.19.66-Re4son+ #1 Sun Aug 18 13:42:02 AEST 2019 armv6l GNU/Linux

**Comment by yrjo** [comment]
`python warberry.py -h
Traceback (most recent call last):
  File "warberry.py", line 19, in <module>
    from src.warberrySetup.Warberry import *
  File "/root/warberry/src/warberrySetup/Warberry.py", line 2, in <module>
    from src.warberrySetup.WarberryInformationGathered import *
  File "/root/warberry/src/warberrySetup/WarberryInformationGathered.py", line 3, in <module>
    from src.core.enumeration.hostnames import *
  File "/root/warberry/src/core/enumeration/hostnames.py", line 21, in <module>
    from dns import resolver
  File "build/bdist.linux-armv6l/egg/dns/resolver.py", line 33, in <module>
  File "build/bdist.linux-armv6l/egg/dns/message.py", line 36, in <module>
  File "build/bdist.linux-armv6l/egg/dns/rrset.py", line 24, in <module>
  File "build/bdist.linux-armv6l/egg/dns/renderer.py", line 26, in <module>
  File "build/bdist.linux-armv6l/egg/dns/tsig.py", line 64, in <module>
  File "build/bdist.linux-armv6l/egg/dns/name.py", line 912, in from_text
struct.error: cannot convert argument to integer`


as  the issue will be most possibly due:
`dnspython requires Python '>=3.4' but the running Python is 2.7.16` warning during installation

**Comment by yrjo** [comment]
well, that can be solved by installing older (python2) version of dnspython,

`pip install dnspython==1.16.0`
that will uninstall (if you do have) newer version 2.x and deploy the older unsupported one, which is needed for warberry.

after doing that, i am able to workaround the issue described above.

cheers.
