### ISSUE TITLE
WAF Enumeration crash 

### ISSUE THREAD

**Issue by JaniEkqvist** [secgroundzero/warberry#59]
Happens on first and subsequent runs. Original RaspBerry, repo is at 
commit b80b4e31964c063caed91ff3cbb5a23ceaa42e64
Author: SecGroundZero <secgroundzero@gmail.com>
Date:   Mon Oct 24 09:47:01 2016 +0000

Also, WAF and Robots_txt running_status printout lines are mixed.

[*] Enumerating WAF on 10.0.0.110
Traceback (most recent call last):
  File "warberry.py", line 306, in <module>
    main()
  File "warberry.py", line 190, in main
    waf_enum(iface)
  File "/home/pi/WarBerry/warberry/src/core/enumeration/services_enum.py", line 141, in waf_enum
    nm.scan(hosts=host, arguments='-Pn -T4 --script http-waf-detect -p80,8080,443,4443,8081,8181,9090 -e ' + iface + '--open -o ../Results/wafed')
  File "/usr/lib/python2.7/dist-packages/nmap/nmap.py", line 302, in scan
    nmap_err_keep_trace = nmap_err_keep_trace)
  File "/usr/lib/python2.7/dist-packages/nmap/nmap.py", line 366, in analyse_nmap_xml_scan
    'command_line': dom.getElementsByTagName('nmaprun')[0].getAttributeNode('args').value,
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by secgroundzero** [comment]
when running the script do you specify an interface or no?

**Comment by JaniEkqvist** [comment]
No, just ran it with defaults:
sudo python warberry.py

**Comment by secgroundzero** [comment]
Pls specify an interface with -I and let me know how it goes.

You shouldnt have issues

**Comment by ikirt** [comment]
I run specifying the interface and have run into this several times now.

sudo ./warberry.py -I wlan0 -P

[*] Enumerating WAF on 10.10.10.1
Traceback (most recent call last):
  File "./warberry.py", line 304, in <module>
    main()
  File "./warberry.py", line 188, in main
    waf_enum(iface)
  File "/home/pi/WarBerry/WarBerry/warberry/src/core/enumeration/services_enum.py", line 141, in waf_enum
    nm.scan(hosts=host, arguments='-Pn -T4 --script http-waf-detect -p80,8080,443,4443,8081,8181,9090 -e ' + iface + '--open -o ../Results/wafed')
  File "/usr/lib/python2.7/dist-packages/nmap/nmap.py", line 302, in scan
    nmap_err_keep_trace = nmap_err_keep_trace)
  File "/usr/lib/python2.7/dist-packages/nmap/nmap.py", line 366, in analyse_nmap_xml_scan
    'command_line': dom.getElementsByTagName('nmaprun')[0].getAttributeNode('args').value,
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by secgroundzero** [comment]
yep the error is pretty obvious. fixed and code and pushing an update shortly. thank you

**Comment by secgroundzero** [comment]
update pushed
