### ISSUE TITLE
nmap not found in path

### ISSUE THREAD

**Issue by Vancer** [secgroundzero/warberry#75]
After the nameserver enumeration function, it pops an error with this saying

```
[+] Scanning for Windows Hosts ...
Traceback (most recent call last):
  File "warberry.py", line 308, in <module>
    main()
  File "warberry.py", line 173, in main
    single_port_scanner(CIDR, intensity, iface)
  File "/home/pi/WarBerry/warberry/src/core/scanners/targetted_scanner.py", line 73, in single_port_scanner
    scanner(name[i], path_file[i], port[i], message[i], result_file[i], CIDR, intensity, scan_type[i],hostlist, iface=iface)
  File "/home/pi/WarBerry/warberry/src/core/scanners/targetted_scanner.py", line 34, in scanner
    nm = nmap.PortScanner()
  File "/usr/lib/python2.7/dist-packages/nmap/nmap.py", line 180, in __init__
    raise PortScannerError('nmap program was not found in path. PATH is : {0}'.format(os.getenv('PATH')))
nmap.nmap.PortScannerError: 'nmap program was not found in path. PATH is : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

**Comment by fartsrainbows** [comment]
Looks like nmap didn't install or is missing from your path PATH is : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Nmap is installed during setup, I see it on line 31 in the bootstrap file.

31 `apt-get install nmap -y `

Check to see if nmap is installed:
`$ dpkg --get-selections|grep nmap
nmap						install
`
