### ISSUE TITLE
Installation doesn't work anymore

### ISSUE THREAD

**Issue by BassdoxXx** [secgroundzero/warberry#84]
In ealier versions of WarBerry I always used this bootstrip.sh file to install the whole thing.

But without it it's not possible for me anymore.
If I do the installation manually with your explanation I didn't get it working.
Everytime I try using "sudo python warberry.py -h"

I get: 
"
Traceback (most recent call last):
  File "run_responder.py", line 32, in <module>
    main()
  File "run_responder.py", line 26, in main
    stdout = open("../Results/responder_output", "wb")
IOError: [Errno 2] No such file or directory: '../Results/responder_output'
Traceback (most recent call last):
  File "wrapper.py", line 33, in <module>
    from src.core.enumeration.ip_enum import *
  File "/home/pi/warberry/src/core/enumeration/ip_enum.py", line 17, in <module>
    from src.core.bypass.static import *
  File "/home/pi/warberry/src/core/bypass/static.py", line 17, in <module>
    from src.utils.utils import *
  File "/home/pi/warberry/src/utils/utils.py", line 24, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
Waiting for Responder to finish!!!
Responder has Finished. Results in ../Results/responder_output
Killed
"

**Comment by mailergfp** [comment]
me too

**Comment by secgroundzero** [comment]
the error message states that you need prettytable. have you tried pip install prettytable?

**Comment by secgroundzero** [comment]
try the new setup.sh script
